# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: britter at ASF
email: britter@apache.org
description: > # this means to ignore newlines until "baseurl:"
  Personal committer page of Benedikt Ritter
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://home.apache.org/~britter" # the base hostname & protocol for your site
twitter_username: BenediktRitter
github_username:  britter

# Build settings
markdown: kramdown
